### ISSUE TITLE
Desync

### ISSUE THREAD

**Issue by Nachtfalter** [lluchs/ClonkMars#13]
Vermutlich weil ich angefangen habe zu brennen. Temperaturzeugs?

**Comment by lluchs** [comment]
Hast du eine Aufnahme?

**Comment by Nachtfalter** [comment]
https://dl.dropboxusercontent.com/u/7324949/451-06_Chasma.c4s

**Comment by lluchs** [comment]
Hrm, beide Aufnahmen haben einen Desync schon bevor bei uns das Spiel abgebrochen ist :(

**Comment by lluchs** [comment]
Jetzt dürfte zumindest nicht mehr sofort ein Desync auftreten, wenn ein Clonk nur bei einem Client anfängt zu brennen. Wenn der Clonk dann aber stirbt, gibt es vermutlich trotzdem einen Desync...

Ich tappe da halt ziemlich im Dunkeln, woher das Problem kommt und kann es auch nicht wirklich vernünftig testen.

**Comment by Nachtfalter** [comment]
Wir könnten es evtl. heute ja mal versuchen herauszufinden, indem wir solche Situationen provozieren.

**Comment by lluchs** [comment]
Definitiv nicht gefixt. In unserem Spiel heute sind zwei Spieler rausgeflogen.

Sven meinte, dass möglicherweise die vielen Effekte daran schuld sind. Ich werde das Temperatursystem mal umschreiben.

**Comment by lluchs** [comment]
2d6c296 scheint tatsächlich geholfen zu haben. In mehreren Testspielen der alaoe-Leute ist kein Desync mehr aufgetreten.
