### ISSUE TITLE
Breite nach Spielerzahl: Ligaproblem?

### ISSUE THREAD

**Issue by Nachtfalter** [lluchs/ClonkMars#21]
Ich weiß nicht, ob es fair ist das anzuwenden, da mehr Spieler ja nicht automatisch bedeutet dass es einfacher wird.

Im Nicht-Liga-Modus würde ich aber ungern darauf verzichten. Kann man da was machen?

Betrifft Kasei und Fossae.

**Comment by lluchs** [comment]
Ich habe gehört, dass das Feature generell etwas doof ist, weil die Breite nicht linear, sondern exponentiell mit der Spielerzahl wächst oder so. Bei vier Spielern ist die Karte also sehr groß im Vergleich zu einem oder zwei Spielern.

Irgendwelches Gehacke mit Sections wie in Blobby fände ich aber nicht so toll.
