### ISSUE TITLE
Thorn.c4d fertigmachen

### ISSUE THREAD

**Issue by Nachtfalter** [lluchs/ClonkMars#22]
Da die Oberfläche von Phobos noch verbesserungswürdig ist habe ich mal ein Dorn-Objekt hinzugefügt. Im Prinzip umgedrehte Stalaktiten.

Was noch fehlt:
- SolidMask geht nur wenn das Objekt gerade nicht rotiert ist (kann man ja vom Splitter übernehmen soweit ich das verstanden habe)
- Sollten die Dinger Schaden nehmen, sollten sie zerbrechen (Meteorit, Flint)
- sollten nur auf Stein wachsen
- eventuell langsam nachwachsen auf der Oberfläche (hat was von einer organischen Landschaft, die sich wehrt!). Wenn man total fies ist, dann wachsen die nicht langsam nach sondern schießen zufällig urplötzlich aus dem Boden (mit Staubeffekt!). Wie eine Falle quasi. Könnte sich vielleicht mit einem Knacken ankündigen. Damit es nicht ganz overkill ist könnte der Clonk nur wegflingen, anstatt aufgespießt zu werden.

**Comment by lluchs** [comment]
Soundeffekt noch!

**Comment by lluchs** [comment]
Der Soundeffekt ist super <3
