### ISSUE TITLE
Panelupgrade manuell anbringen

### ISSUE THREAD

**Issue by lluchs** [lluchs/ClonkMars#39]
Via Kontextmenü und dann etwas rumschweißen.

**Comment by Nachtfalter** [comment]
Dafür.

**Comment by lluchs** [comment]
Wobei wir dann auch einen grafischen Unterschied zwischen normalen und verbesserten Panels brauchen. Hattest du da nicht schon mal was gemacht? Oder war das nur für die [Upgrade-Grafik](https://github.com/lluchs/ClonkMars/blob/5be8b01924cd0fbeaddd0bd2698fa18da3be6299/ClonkMars.c4d/Structures.c4d/Lab.c4d/Upgrades.c4d/SuperPanel.c4d/Graphics.png)?

**Comment by lluchs** [comment]
Hm, wenn ich es recht sehe, ist der Unterschied dabei auch nur diese zwei Dinger unten. Die könnte man auch recht gut per Overlay dranpappen. Kannst du die vielleicht getrennt hinzufügen?
