### ISSUE TITLE
Phobos spielbar machen

### ISSUE THREAD

**Issue by lluchs** [lluchs/ClonkMars#5]
http://clonkforge.net/bugtrack.php?shbug=12628

...oder beweisen, dass es spielbar ist!

**Comment by lluchs** [comment]
Idee: Wenn alle Clonks tot sind, kommt man in's Kaufmenü und fliegt dann zusammen mit den bestellten Sachen wieder zurück. Wenn das Geld alle ist und man somit keine neue Basis etc. mehr bauen kann, hat man dann natürlich trotzdem verloren.

**Comment by Nachtfalter** [comment]
Interessante Idee. Klingt aber nicht allzu intuitiv (was nicht zwingend was schlimmes ist).

**Comment by lluchs** [comment]
Noch kein Kaufmenü, aber wenn alle Clonks sterben, wird der zuletzt gestorbene Clonk jetzt reproduziert.

Vielleicht können wir ja so mal versuchen, ob wir Phobos schaffen können..!

**Comment by Nachtfalter** [comment]
Done
