### ISSUE TITLE
HUD verbessern

### ISSUE THREAD

**Issue by lluchs** [lluchs/ClonkMars#6]
- Temperatur und Itemlog ändern sich nicht und müssen deshalb auf der Basisgrafik nicht ausgeschnitten werden
- Beim Reproduktions-Part ist zu wenig ausgeschnitten. Man sieht immer ganz rechts ein Teil der Doppelhelix und des "%".

**Comment by Nachtfalter** [comment]
Das war recht kompliziert. Ich weiß nicht mehr ob ich mich wirklich darin verwursten will :(
