### ISSUE TITLE
Kristalle: Besseres Rotate

### ISSUE THREAD

**Issue by Nachtfalter** [lluchs/ClonkMars#7]
Es wäre schön, wenn Kristalle sich besser an ihre Landschaft ansaugen würden. Manchmal stehen die Ecken ganz schön ab. Ich bin mir nicht sicher ob man das mit einer besseren Verticeverteilung ganz schnell lösen könnte.

**Comment by lluchs** [comment]
![Verticesbild](http://i.imgur.com/bcDBkte.png) - ja, ich glaube, da lässt sich tatsächlich was tun.

**Comment by Nachtfalter** [comment]
Außerdem sollten sie vielleicht nicht in Lava wachsen!
